### ISSUE TITLE
could you please fix

### ISSUE THREAD

**Issue by iruzevic** [infinum/coding-standards-wp#4]
FILE: ...inum/wp-boilerplate/wp-content/themes/theme_name/inc/helpers.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | Missing file doc comment
   |       | (Squiz.Commenting.FileComment.Missing)
----------------------------------------------------------------------

<img width="359" alt="screen shot 2017-07-18 at 15 41 36" src="https://user-images.githubusercontent.com/23283324/28319968-a29a6fa2-6bcf-11e7-8084-5aaf279e67fb.png">
<img width="636" alt="screen shot 2017-07-18 at 15 41 47" src="https://user-images.githubusercontent.com/23283324/28319969-a29daeb0-6bcf-11e7-8c22-4097cc26c80b.png">

**Comment by dingo-d** [comment]
This comes because every `include`/`require` statement should have its own docblock. So the easiest fix is 

~~~php
<?php
/**
 * Include Helpers from files
 *
 * @package theme_name
 */

/**
 * Require statements
 */
require_once( get_stylesheet_directory() . '/inc/helpers/excerpt.php' );
require_once( get_stylesheet_directory() . '/inc/helpers/general.php' );
require_once( get_stylesheet_directory() . '/inc/helpers/html-modifier.php' );
require_once( get_stylesheet_directory() . '/inc/helpers/images.php' );
require_once( get_stylesheet_directory() . '/inc/helpers/post-type.php' );
require_once( get_stylesheet_directory() . '/inc/helpers/wp-gallery.php' );
~~~
